baseurl = "https://moritzgraf.de/"
languageCode = "de-de"
title = "Moritz Graf"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Moritz Graf"
	description = "What Moritz does for work"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "moritz_123.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Hixxx, I'm Moritz.**<br>Want to get<br> an impression of<br> what I do at work?"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""
		xing = ""

		copyright = [
			"&copy; Moritz Graf",
			"Blog: [iptize](https://iptize.it)",
			"Social: [Xing](https://xing.com/profile/Moritz_Graf4/) | [LinkedIn](https://de.linkedin.com/in/moritz-graf-92abaa91)"
		]


	[params.about]
		title = "My daily work - Visualized in tag clouds"
		#content = "On a first meetup most people ask me: What you do for work? <br> Answering this question is always pretty difficult... <br>So I came up with this homepage-thing. If anybody is really interested, he can just have a look at the tagclouds bejond this text. They explain all the buzzwords and thechniques I get confronted with every day."


	[params.portfolio]
		#title = "Instead of just forming sentences arround my work I just thought"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/voip_wordcloud.png"
			thumb = "thumbs/voip_wordcloud_thumb.png"
			title = "Voice over IP"
			description = "Sending voice via packet switched networks."

		[[params.portfolio.gallery]]
			image = "fulls/linux_wordcloud.png"
			thumb = "thumbs/linux_wordcloud_thumb.png"
			title = "Linux"
			description = "Basic knowledge for agile IT guys."

		[[params.portfolio.gallery]]
			image = "fulls/monitoring_wordcloud.png"
			thumb = "thumbs/monitoring_wordcloud_thumb.png"
			title = "Monitoring"
			description = "Keep track of what's happening in your network."

		[[params.portfolio.gallery]]
			image = "fulls/networking_wordcloud.png"
			thumb = "thumbs/networking_wordcloud_thumb.png"
			title = "Networking"
			description = "Basics of data transport via packet switched networks."

		[[params.portfolio.gallery]]
			image = "fulls/pots_wordcloud.png"
			thumb = "thumbs/pots_wordcloud_thumb.png"
			title = "Plain old telephone service"
			description = "Circuit switched transport of voice."


#	[params.contact]
#		title = "Get In Touch"
#		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."
#
#		address = [
#			"1234 Somewhere Rd.",
#			"Nashville, TN 00000",
#			"United States"
#		]
#		phone = "000-000-0000"
#
		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
#		email = "hello@example.com"
#
#		[params.contact.form]
#			# Set custom strings for the form if your native
#			# language isn't English
#			name = "Name"
#			email = "Email"
#			message = "Message"
##			submit = "Send message"
